/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'color' : [] | [string],
  'description' : [] | [string],
}
export type CategoryId = bigint;
export interface Document {
  'id' : DocumentId,
  'categoryId' : CategoryId,
  'title' : string,
  'blob' : [] | [ExternalBlob],
  'createdAt' : Time,
  'mimeType' : string,
  'fileName' : string,
  'fileSize' : bigint,
}
export type DocumentId = bigint;
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'createdAt' : Time,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePassword' : ActorMethod<[string, string], { 'ok' : null } | { 'err' : string }>,
  'createCategory' : ActorMethod<
    [
      {
        'name' : string,
        'color' : [] | [string],
        'description' : [] | [string],
      },
    ],
    CategoryId
  >,
  'deleteCategories' : ActorMethod<[Array<CategoryId>], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getDocument' : ActorMethod<[DocumentId], [] | [Document]>,
  'getDocumentsByCategory' : ActorMethod<[CategoryId], Array<Document>>,
  'getUserCategoryCount' : ActorMethod<[Principal], bigint>,
  'getUserDocumentCount' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'register' : ActorMethod<[string, string, [] | [string]], { 'ok' : null } | { 'err' : string }>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDocument' : ActorMethod<
    [
      {
        'categoryId' : CategoryId,
        'title' : string,
        'blob' : ExternalBlob,
        'mimeType' : string,
        'fileName' : string,
        'fileSize' : bigint,
      },
    ],
    DocumentId
  >,
  'updateAdminCode' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'updateCategory' : ActorMethod<
    [
      {
        'id' : CategoryId,
        'name' : string,
        'color' : [] | [string],
        'description' : [] | [string],
      },
    ],
    undefined
  >,
  'verifyLogin' : ActorMethod<[string, string], { 'ok' : UserProfile } | { 'err' : string }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
