/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const DocumentId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Document = IDL.Record({
  'id' : DocumentId,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
  'createdAt' : Time,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
  'createCategory' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'color' : IDL.Opt(IDL.Text),
          'description' : IDL.Opt(IDL.Text),
        }),
      ],
      [CategoryId],
      [],
    ),
  'deleteCategories' : IDL.Func([IDL.Vec(CategoryId)], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
  'getDocumentsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getUserCategoryCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserDocumentCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDocument' : IDL.Func(
      [
        IDL.Record({
          'categoryId' : CategoryId,
          'title' : IDL.Text,
          'blob' : ExternalBlob,
          'mimeType' : IDL.Text,
          'fileName' : IDL.Text,
          'fileSize' : IDL.Nat,
        }),
      ],
      [DocumentId],
      [],
    ),
  'updateAdminCode' : IDL.Func([IDL.Text], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
  'updateCategory' : IDL.Func(
      [
        IDL.Record({
          'id' : CategoryId,
          'name' : IDL.Text,
          'color' : IDL.Opt(IDL.Text),
          'description' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
      [],
    ),
  'verifyLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Variant({'ok': UserProfile, 'err': IDL.Text})], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const DocumentId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Document = IDL.Record({
    'id' : DocumentId,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
    'createdAt' : Time,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
    'createCategory' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'color' : IDL.Opt(IDL.Text),
            'description' : IDL.Opt(IDL.Text),
          }),
        ],
        [CategoryId],
        [],
      ),
    'deleteCategories' : IDL.Func([IDL.Vec(CategoryId)], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
    'getDocumentsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getUserCategoryCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserDocumentCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDocument' : IDL.Func(
        [
          IDL.Record({
            'categoryId' : CategoryId,
            'title' : IDL.Text,
            'blob' : ExternalBlob,
            'mimeType' : IDL.Text,
            'fileName' : IDL.Text,
            'fileSize' : IDL.Nat,
          }),
        ],
        [DocumentId],
        [],
      ),
    'updateAdminCode' : IDL.Func([IDL.Text], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
    'updateCategory' : IDL.Func(
        [
          IDL.Record({
            'id' : CategoryId,
            'name' : IDL.Text,
            'color' : IDL.Opt(IDL.Text),
            'description' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
        [],
      ),
    'verifyLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Variant({'ok': UserProfile, 'err': IDL.Text})], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
